
version: '3'

services:
  laravel:
    build:
      context: ./
      dockerfile: Dockerfile
    image: my-laravel-app
    ports:
      - "9000:9000"
    working_dir: /var/www
    volumes:
      - ./:/var/www 
    networks:
      - laravel-network
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - dbdata:/var/lib/mysql 
    networks:
      - laravel-network

networks:
  laravel-network:

volumes:
  dbdata:
    driver: local